services:
  - type: web
    name: finance-monitor-backend
    env: python
    repo: https://github.com/Muhammad-Sheraz-ds/financial-moniotor
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    workingDir: backend
    envVars:
      - key: "GROQ_API_KEY"
        value: "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"






















